Add kotlinx json serialization support
faogustavo/kached pull request #21
Opened 2020-10-29 22:21 UTC by enzo-beltrami

Closes #3

2020-10-29 23:31 UTC, faogustavo requested changes
Nice man, thanks.
Just fix the KTLint and extract the hardcoded library to the dependencies file please

2020-10-29 23:31 UTC, faogustavo commented on serializer/kotlinx-json-serializer/build.gradle.kts
> +                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.0.1")
Please, add this to the Dependencies.kt file

2020-10-29 23:59 UTC, enzo-beltrami commented
> Nice man, thanks.
> Just fix the KTLint and extract the hardcoded library to the dependencies file please

Just fixed it, however there's still an error on Gradle and I don't know how to fix it :thinking: 

```
Could not create an instance of type org.jetbrains.kotlin.gradle.targets.js.subtargets.KotlinBrowserJs.
```

2020-10-30 09:05 UTC, faogustavo commented
@enzo-beltrami just comment out the JS setup in the Gradle file and after the merge, I'll investigate this

2020-10-30 09:28 UTC, faogustavo approved these changes

2020-10-30 09:29 UTC, merged